# -*- coding: utf-8 -*-
"""Webscraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i1TnfoK4B5S2hCAhtiavzumj8hmKZNtM
"""

!pip install cloudscraper

from bs4 import BeautifulSoup
import cloudscraper
scraper = cloudscraper.create_scraper(delay=10,   browser={'custom': 'ScraperBot/1.0',})
url = 'https://www.forexfactory.com/calendar'
r = scraper.get(url)

soup = BeautifulSoup(r.text,'lxml')

calendar_table = soup.find('table', class_="calendar__table")



#print(calendar_table)

for row in calendar_table.select('tr[class*="calendar__row calendar_row"]'):
     row_data = [td.get_text(strip=True) for td in row.find_all('td')]
     print(row_data)

from bs4 import BeautifulSoup
import cloudscraper
import pandas as pd
scraper = cloudscraper.create_scraper(delay=10,   browser={'custom': 'ScraperBot/1.0',})
url = 'https://www.forexfactory.com/calendar'
r = scraper.get(url)

soup = BeautifulSoup(r.text,'lxml')

calendar_table = soup.find('table', class_="calendar__table")

#print(calendar_table)
column_headers = ['Date', 'Time', 'void', 'Currency', 'Impact', 'Event', 'Detail_void', 'Actual', 'Forecast', 'Previous', 'Graph_void']
date = ''
time = ''
void = ''
currency = ''# -*- coding: utf-8 -*-
"""Webscraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i1TnfoK4B5S2hCAhtiavzumj8hmKZNtM
"""

!pip install cloudscraper

import cloudscraper
from bs4 import BeautifulSoup

with cloudscraper.create_scraper(delay=10, browser={'custom': 'ScraperBot/1.0'}) as scraper:
    r = scraper.get('https://www.forexfactory.com/calendar')

    soup = BeautifulSoup(r.text, 'html.parser')
    #store the security value in a variable incase it changes
    #from the html code
    security_value = soup.find('input', {'name': 'flex[Calendar_mainCal][modelData]'})['value'] 

    print(security_value)

    #from developer tools > network > flex.php (main network) > payload > view_source
    data = f'securitytoken=guest&do=saveoptions&setdefault=no&ignoreinput=no&flex%5BCalendar_mainCal%5D%5BidSuffix%5D=&flex%5BCalendar_mainCal%5D%5B_flexForm_%5D=flexForm&flex%5BCalendar_mainCal%5D%5BmodelData%5D={security_value}&flex%5BCalendar_mainCal%5D%5Bbegindate%5D=January+29%2C+2023&flex%5BCalendar_mainCal%5D%5Benddate%5D=February+4%2C+2023&flex%5BCalendar_mainCal%5D%5Bcalendardefault%5D=thisweek&flex%5BCalendar_mainCal%5D%5Bimpacts%5D%5Bhigh%5D=high&flex%5BCalendar_mainCal%5D%5B_cbarray_%5D=1&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bgrowth%5D=growth&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Binflation%5D=inflation&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bemployment%5D=employment&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bcentralbank%5D=centralbank&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bbonds%5D=bonds&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bhousing%5D=housing&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bsentiment%5D=sentiment&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bpmi%5D=pmi&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bspeeches%5D=speeches&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bmisc%5D=misc&flex%5BCalendar_mainCal%5D%5B_cbarray_%5D=1&flex%5BCalendar_mainCal%5D%5Bcurrencies%5D%5Beur%5D=eur&flex%5BCalendar_mainCal%5D%5Bcurrencies%5D%5Bgbp%5D=gbp&flex%5BCalendar_mainCal%5D%5Bcurrencies%5D%5Busd%5D=usd&flex%5BCalendar_mainCal%5D%5B_cbarray_%5D=1&false'
    
    #copy the request headers
    #exclude use-agent since cloud scrapper already covers it
    headers = {
        'authority': 'www.forexfactory.com',
        'method': 'POST',
        'path': '/flex.php?',
        'scheme': 'https',
        'accept': '/',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
        'content-length': '1974',
        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'origin': 'https://www.forexfactory.com',
        'referer': 'https://www.forexfactory.com/calendar',
        'sec-ch-ua': '"Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"macOS"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'x-requested-with': 'XMLHttpRequest'
    }
    r = scraper.post('https://www.forexfactory.com/flex.php?', data=data, headers=headers) #use request URL

    soup = BeautifulSoup(r.text,'lxml')

    calendar_table = soup.find('table', class_="calendar__table")

    #print(calendar_table)
    column_headers = ['Date', 'Time', 'void', 'Currency', 'Impact', 'Event', 'Detail_void', 'Actual', 'Forecast', 'Previous', 'Graph_void']
    df = pd.DataFrame(columns = column_headers)
    for row in calendar_table.select('tr[class*="calendar__row calendar_row"]'):
        row_data = [td.get_text(strip=True) for td in row.find_all('td')]
        print(row_data)

import cloudscraper
from bs4 import BeautifulSoup

with cloudscraper.create_scraper(delay=10, browser={'custom': 'ScraperBot/1.0'}) as scraper:
    r = scraper.get('https://www.forexfactory.com/calendar')

    soup = BeautifulSoup(r.text, 'html.parser')
    #store the security value in a variable incase it changes
    #from the html code
    security_value = soup.find('input', {'name': 'flex[Calendar_mainCal][modelData]'})['value'] 

    #print(security_value)

    #from developer tools > network > flex.php (main network) > payload > view_source
    data = f'securitytoken=guest&do=saveoptions&setdefault=no&ignoreinput=no&flex%5BCalendar_mainCal%5D%5BidSuffix%5D=&flex%5BCalendar_mainCal%5D%5B_flexForm_%5D=flexForm&flex%5BCalendar_mainCal%5D%5BmodelData%5D={security_value}&flex%5BCalendar_mainCal%5D%5Bbegindate%5D=January+29%2C+2023&flex%5BCalendar_mainCal%5D%5Benddate%5D=February+4%2C+2023&flex%5BCalendar_mainCal%5D%5Bcalendardefault%5D=thisweek&flex%5BCalendar_mainCal%5D%5Bimpacts%5D%5Bhigh%5D=high&flex%5BCalendar_mainCal%5D%5B_cbarray_%5D=1&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bgrowth%5D=growth&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Binflation%5D=inflation&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bemployment%5D=employment&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bcentralbank%5D=centralbank&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bbonds%5D=bonds&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bhousing%5D=housing&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bsentiment%5D=sentiment&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bpmi%5D=pmi&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bspeeches%5D=speeches&flex%5BCalendar_mainCal%5D%5Beventtypes%5D%5Bmisc%5D=misc&flex%5BCalendar_mainCal%5D%5B_cbarray_%5D=1&flex%5BCalendar_mainCal%5D%5Bcurrencies%5D%5Beur%5D=eur&flex%5BCalendar_mainCal%5D%5Bcurrencies%5D%5Bgbp%5D=gbp&flex%5BCalendar_mainCal%5D%5Bcurrencies%5D%5Busd%5D=usd&flex%5BCalendar_mainCal%5D%5B_cbarray_%5D=1&false'
    
    #copy the request headers
    #exclude use-agent since cloud scrapper already covers it
    headers = {
        'authority': 'www.forexfactory.com',
        'method': 'POST',
        'path': '/flex.php?',
        'scheme': 'https',
        'accept': '/',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
        'content-length': '1974',
        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'origin': 'https://www.forexfactory.com',
        'referer': 'https://www.forexfactory.com/calendar',
        'sec-ch-ua': '"Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"macOS"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'x-requested-with': 'XMLHttpRequest'
    }
    r = scraper.post('https://www.forexfactory.com/flex.php?', data=data, headers=headers) #use request URL

    soup = BeautifulSoup(r.text,'lxml')

    calendar_table = soup.find('table', class_="calendar__table")

    #print(calendar_table)
    column_headers = ['Date', 'Time', 'void', 'Currency', 'Impact', 'Event', 'Detail_void', 'Actual', 'Forecast', 'Previous', 'Graph_void']
    df = pd.DataFrame(columns = column_headers)
    for row in calendar_table.select('tr[class*="calendar__row calendar_row"]'):
        row_data = [td.get_text(strip=True) for td in row.find_all('td')]
        df.loc[len(df)] = row_data
df

#drop the columns with no data
df.drop(columns=['void', 'Detail_void', 'Graph_void', 'Impact'], inplace=True)

#Deletion and imputation
df['Date'].replace(to_replace='', value=None, method='ffill', inplace=True) #fill empty dates with previous data
df['Time'].replace(to_replace='', value=None, method='ffill', inplace=True) #fill empty times with previous data
df.drop(labels=df[df['Event'] == ''].index, inplace=True) #drop rows with no events\

df

from bs4 import BeautifulSoup
import cloudscraper
import pandas as pd
scraper = cloudscraper.create_scraper(delay=10,   browser={'custom': 'ScraperBot/1.0',})
url = 'https://www.forexfactory.com/calendar'
r = scraper.get(url)

soup = BeautifulSoup(r.text,'lxml')

calendar_table = soup.find('table', class_="calendar__table")

#print(calendar_table)
column_headers = ['Date', 'Time', 'void', 'Currency', 'Impact', 'Event', 'Detail_void', 'Actual', 'Forecast', 'Previous', 'Graph_void']
df = pd.DataFrame(columns = column_headers)
for row in calendar_table.select('tr[class*="calendar__row calendar_row"]'):
     row_data = [td.get_text(strip=True) for td in row.find_all('td')]
     df.loc[len(df)] = row_data
  
df
impact = ''
event = ''
detail_void = ''
actual = ''
forcast = ''
previous = ''
graph_void = ''
df = pd.DataFrame(columns = column_headers)
for row in calendar_table.select('tr[class*="calendar__row calendar_row"]'):
     row_data = [td.get_text(strip=True) for td in row.find_all('td')]
     df.loc[len(df)] = row_data
  
df

from bs4 import BeautifulSoup
import cloudscraper
import pandas as pd
scraper = cloudscraper.create_scraper(delay=10,   browser={'custom': 'ScraperBot/1.0',})
url = 'https://www.forexfactory.com/calendar#closed'
r = scraper.get(url)

soup = BeautifulSoup(r.text,'lxml')

calendar_table = soup.find('table', class_="calendar__table")

#print(calendar_table)
column_headers = ['Date', 'Time', 'void', 'Currency', 'Impact', 'Event', 'Detail_void', 'Actual', 'Forecast', 'Previous', 'Graph_void']
date = ''
time = ''
void = ''
currency = ''
impact = ''
event = ''
detail_void = ''
actual = ''
forcast = ''
previous = ''
graph_void = ''
df = pd.DataFrame(columns = column_headers)
for row in calendar_table.select('tr[class*="calendar__row calendar_row"]'):
     row_data = [td.get_text(strip=True) for td in row.find_all('td')]
     df.loc[len(df)] = row_data
  
df
