# This is a basic workflow to help you get started with Actions

name: Jupyter

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '*/6 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: repo 
        name: Repo Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - id: python
        name: Python Setup & Packages Installation
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - id: python_script
        name: Python Script Execution
        run: python main.py
        shell: bash
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Commit and push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTIONS_PUSH_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          commit_options: "--all"
